---@meta

---@alias blob number
---@alias buffer number|string
---@alias channel number
---@alias float number
---@alias job number
---@alias object any
---@alias sends number
---@alias tabpage number
---@alias window number
