---@meta

---@alias blob number
---@alias buffer integer|string
---@alias channel integer
---@alias float number
---@alias job number
---@alias object any
---@alias sends number
---@alias tabpage integer
---@alias window integer
